//
export const GET_TOP_ARTISTS_LOADING = "GET_TOP_ARTISTS_LOADING";
export const GET_TOP_ARTISTS_SUCCESS = "GET_TOP_ARTISTS_SUCCESS";
export const GET_TOP_ARTISTS_ERROR = "GET_TOP_ARTISTS_ERROR";
//
export const GET_SINGLE_ARTIST_LOADING = "GET_SINGLE_ARTIST_LOADING";
export const GET_SINGLE_ARTIST_SUCCESS = "GET_SINGLE_ARTIST_SUCCESS";
export const GET_SINGLE_ARTIST_ERROR = "GET_SINGLE_ARTIST_ERROR";
//
export const GET_ALBUMS_ARTIST_LOADING = "GET_ALBUMS_ARTIST_LOADING";
export const GET_ALBUMS_ARTIST_SUCCESS = "GET_ALBUMS_ARTIST_SUCCESS";
export const GET_ALBUMS_ARTIST_ERROR = "GET_ALBUMS_ARTIST_ERROR";
//
export const GET_TOP_ARTIST_TRACKS_LOADING = "GET_TOP_ARTIST_TRACKS_LOADING";
export const GET_TOP_ARTIST_TRACKS_SUCCESS = "GET_TOP_ARTIST_TRACKS_SUCCESS";
export const GET_TOP_ARTIST_TRACKS_ERROR = "GET_TOP_ARTIST_TRACKS_ERROR";
//
export const GET_RELATED_ARTISTS_LOADING = "GET_RELATED_ARTISTS_LOADING";
export const GET_RELATED_ARTISTS_SUCCESS = "GET_RELATED_ARTISTS_SUCCESS";
export const GET_RELATED_ARTISTS_ERROR = "GET_RELATED_ARTISTS_ERROR";
//
export const GET_SINGLE_ALBUM_LOADING = "GET_SINGLE_ALBUM_LOADING";
export const GET_SINGLE_ALBUM_SUCCESS = "GET_SINGLE_ALBUM_SUCCESS";
export const GET_SINGLE_ALBUM_ERROR = "GET_SINGLE_ALBUM_ERROR";
//
export const SEARCH_ARTISTS_LOADING = "SEARCH_ARTISTS_LOADING";
export const SEARCH_ARTISTS_SUCCESS = "SEARCH_ARTISTS_SUCCESS";
export const SEARCH_ARTISTS_ERROR = "SEARCH_ARTISTS_ERROR";
//
export const SEARCH_ALBUMS_LOADING = "SEARCH_ALBUMS_LOADING";
export const SEARCH_ALBUMS_SUCCESS = "SEARCH_ALBUMS_SUCCESS";
export const SEARCH_ALBUMS_ERROR = "SEARCH_ALBUMS_ERROR";
//
export const SEARCH_TRACKS_LOADING = "SEARCH_TRACKS_LOADING";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_ERROR = "SEARCH_TRACKS_ERROR";
//
export const GET_GENRES_LOADING = "GET_GENRES_LOADING";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";
//
export const GET_TOP_RADIOS_LOADING = "GET_TOP_RADIOS_LOADING";
export const GET_TOP_RADIOS_SUCCESS = "GET_TOP_RADIOS_SUCCESS";
export const GET_TOP_RADIOS_ERROR = "GET_TOP_RADIOS_ERROR";
//
export const GET_RADIO_LOADING = "GET_RADIO_LOADING";
export const GET_RADIO_SUCCESS = "GET_RADIO_SUCCESS";
export const GET_RADIO_ERROR = "GET_RADIO_ERROR";
//
export const GET_ARTISTS_BY_GENRE_LOADING = "GET_ARTISTS_BY_GENRE_LOADING";
export const GET_ARTISTS_BY_GENRE_SUCCESS = "GET_ARTISTS_BY_GENRE_SUCCESS";
export const GET_ARTISTS_BY_GENRE_ERROR = "GET_ARTISTS_BY_GENRE_ERROR";
//
export const ADD_FAVORITE_SONG = "ADD_FAVORITE_SONG";
export const REMOVE_FAVORITE_SONG = "REMOVE_FAVORITE_SONG";